-- DROP DATABASE IF EXISTS Academy;

-- CREATE DATABASE Academy;

DROP TABLE IF EXISTS Spartans;

CREATE TABLE Spartans (
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(4) NOT NULL,
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	Course VARCHAR(20) DEFAULT NULL,
	GradeAchieved VARCHAR(20) DEFAULT NULL,
	CityOfResidence VARCHAR(20) NOT NULL,
	DateJoined DATE NOT NULL,
	Stream INT NOT NULL,
	HasGraduated BIT DEFAULT 0,
	IsOnSite BIT DEFAULT 0,
	OnSiteAt INT DEFAULT NULL
);

DROP TABLE IF EXISTS University;

CREATE TABLE University (
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(120) NOT NULL,
	City VARCHAR(20) NOT NULL,
	Country VARCHAR(20) DEFAULT 'UK'
);

DROP TABLE IF EXISTS SpartanUniversities;

CREATE TABLE SpartanUniversities (
	SpartanID INT FOREIGN KEY REFERENCES Spartans(Id),
	UniversityID INT FOREIGN KEY REFERENCES University(Id)
);


DROP TABLE IF EXISTS Stream;

CREATE TABLE Stream (
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(50) NOT NULL,
);

DROP TABLE IF EXISTS Trainer;

CREATE TABLE Trainer (
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(4) NOT NULL,
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS StreamTrainers;

CREATE TABLE StreamTrainers (
	StreamId INT FOREIGN KEY REFERENCES Stream(Id),
	TrainerId INT FOREIGN KEY REFERENCES Trainer(Id)
);

DROP TABLE IF EXISTS SpartanTrainers;

CREATE TABLE SpartanTrainers (
	SpartanId INT FOREIGN KEY REFERENCES Spartans(Id),
	TrainerId INT FOREIGN KEY REFERENCES Trainer(Id)
);

DROP TABLE IF EXISTS Site;

CREATE TABLE Site (
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR (50) NOT NULL,
	City VARCHAR(20) NOT NULL,
	ContactName VARCHAR(120) NOT NULL,
	ContactNumber CHAR(11) NOT NULL
);